name: apptentive_flutter
description: Plugin for using Apptentive with Flutter
version: 0.0.1
homepage: https://github.com/eBay/flutter_glove_box/
repository: https://github.com/eBay/flutter_glove_box/tree/master/packages/apptentive_flutter
issue_tracker: https://github.com/eBay/flutter_glove_box/issues

environment:
  flutter: 1.12.13+hotfix.5
  sdk: 2.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.apptentive_flutter
    pluginClass: ApptentiveFlutterPlugin
